var COLOR_CACHE = {
	"aliceblue" : "black",
	"antiquewhite" : "black",
	"aqua" : "black",
	"aquamarine" : "black",
	"azure" : "black",
	"beige" : "black",
	"bisque" : "black",
	"black" : "white",
	"blanchedalmond" : "black",
	"blue" : "white",
	"blueviolet" : "white",
	"brown" : "white",
	"burlywood" : "black",
	"cadetblue" : "black",
	"chartreuse" : "black",
	"chocolate" : "black",
	"coral" : "black",
	"cornflowerblue" : "black",
	"cornsilk" : "black",
	"crimson" : "white",
	"cyan" : "black",
	"darkblue" : "white",
	"darkcyan" : "black",
	"darkgoldenrod" : "black",
	"darkgray" : "black",
	"darkgrey" : "black",
	"darkgreen" : "white",
	"darkkhaki" : "black",
	"darkmagenta" : "white",
	"darkolivegreen" : "white",
	"darkorange" : "black",
	"darkorchid" : "white",
	"darkred" : "white",
	"darksalmon" : "black",
	"darkseagreen" : "black",
	"darkslateblue" : "white",
	"darkslategray" : "white",
	"darkslategrey" : "white",
	"darkturquoise" : "black",
	"darkviolet" : "white",
	"deeppink" : "black",
	"deepskyblue" : "black",
	"dimgray" : "white",
	"dimgrey" : "white",
	"dodgerblue" : "black",
	"firebrick" : "white",
	"floralwhite" : "black",
	"forestgreen" : "black",
	"fuchsia" : "black",
	"gainsboro" : "black",
	"ghostwhite" : "black",
	"gold" : "black",
	"goldenrod" : "black",
	"gray" : "black",
	"grey" : "black",
	"green" : "white",
	"greenyellow" : "black",
	"honeydew" : "black",
	"hotpink" : "black",
	"indianred" : "black",
	"indigo" : "white",
	"ivory" : "black",
	"khaki" : "black",
	"lavender" : "black",
	"lavenderblush" : "black",
	"lawngreen" : "black",
	"lemonchiffon" : "black",
	"lightblue" : "black",
	"lightcoral" : "black",
	"lightcyan" : "black",
	"lightgoldenrodyellow" : "black",
	"lightgray" : "black",
	"lightgrey" : "black",
	"lightgreen" : "black",
	"lightpink" : "black",
	"lightsalmon" : "black",
	"lightseagreen" : "black",
	"lightskyblue" : "black",
	"lightslategray" : "black",
	"lightslategrey" : "black",
	"lightsteelblue" : "black",
	"lightyellow" : "black",
	"lime" : "black",
	"limegreen" : "black",
	"linen" : "black",
	"magenta" : "black",
	"maroon" : "white",
	"mediumaquamarine" : "black",
	"mediumblue" : "white",
	"mediumorchid" : "black",
	"mediumpurple" : "black",
	"mediumseagreen" : "black",
	"mediumslateblue" : "black",
	"mediumspringgreen" : "black",
	"mediumturquoise" : "black",
	"mediumvioletred" : "white",
	"midnightblue" : "white",
	"mintcream" : "black",
	"mistyrose" : "black",
	"moccasin" : "black",
	"navajowhite" : "black",
	"navy" : "white",
	"oldlace" : "black",
	"olive" : "black",
	"olivedrab" : "black",
	"orange" : "black",
	"orangered" : "black",
	"orchid" : "black",
	"palegoldenrod" : "black",
	"palegreen" : "black",
	"paleturquoise" : "black",
	"palevioletred" : "black",
	"papayawhip" : "black",
	"peachpuff" : "black",
	"peru" : "black",
	"pink" : "black",
	"plum" : "black",
	"powderblue" : "black",
	"purple" : "white",
	"rebeccapurple" : "white",
	"red" : "black",
	"rosybrown" : "black",
	"royalblue" : "white",
	"saddlebrown" : "white",
	"salmon" : "black",
	"sandybrown" : "black",
	"seagreen" : "black",
	"seashell" : "black",
	"sienna" : "white",
	"silver" : "black",
	"skyblue" : "black",
	"slateblue" : "white",
	"slategray" : "black",
	"slategrey" : "black",
	"snow" : "black",
	"springgreen" : "black",
	"steelblue" : "black",
	"tan" : "black",
	"teal" : "white",
	"thistle" : "black",
	"tomato" : "black",
	"turquoise" : "black",
	"violet" : "black",
	"wheat" : "black",
	"white" : "black",
	"whitesmoke" : "black",
	"yellow" : "black",
	"yellowgreen" : "black"
};

function parseRGB(color) {
	var rgbMatch = /rgb\(([0-9]+),([0-9]+),([0-9]+)\)/.exec(color.replace(/\s/g, ''));
	if (rgbMatch) {
		return rgbMatch.slice(1, 4).map(Number);
	}
	var hexMatch = /#([0-9A-Z]{2})([0-9A-Z]{2})([0-9A-Z]{2})/.exec(color)
			|| /#([0-9A-Z])([0-9A-Z])([0-9A-Z])/.exec(color); // for 3-digit hex colors
	if (hexMatch) {
		return hexMatch.slice(1, 4).map(function(hex) {
			return parseInt(hex, 16);
		});
	}
	return [0, 0, 0];
}

// prepare for magic numbers
function getContrasting(color) {
	var found = COLOR_CACHE[color];
	if (found) {
		return found;
	}
	var intensity = parseRGB(color).map(function(component) {
		var percent = component / 255.0;
		return percent <= 0.03928 ? percent / 12.92 : Math.pow((percent + 0.055) / 1.055, 2.4);
	});
	var luminance = 0.2126 * intensity[0] + 0.7152 * intensity[1] + 0.0722 * intensity[2];
	var result = luminance > 0.179 ? 'black' : 'white';
	COLOR_CACHE[color] = result;
	return result;
}
